### ISSUE TITLE
Unsolvable Treehouse Puzzle

### ISSUE THREAD

**Issue by sigma144** [Penguin12335/Variety-Randomizer-2.0.1#1]
![Screenshot 2022-03-30 153646](https://user-images.githubusercontent.com/3487299/160941383-3f01a35a-ccd3-476f-bf11-bdba5478b27b.jpg)
Seed: 4927135
This puzzle on right orange bridge is not solvable to the left exit, which makes the laser impossible. Did you make sure to set the proper obstructions before generating?

**Comment by Penguin12335** [comment]
Oh that's what Obstruction for!!!? I'll have a look, Thanks

**Comment by Penguin12335** [comment]
I lowered the number of stars and Square, this should fix the issue
