### ISSUE TITLE
Keep puzzle doesn't accept solution

### ISSUE THREAD

**Issue by sigma144** [Penguin12335/Variety-Randomizer-2.0.1#2]
![Screenshot 2022-03-30 161117](https://user-images.githubusercontent.com/3487299/160941792-cdffab4e-f604-47d3-93f0-882559657edc.jpg)
Seed: 492713
It doesn't accept the solution even though it is correct. I don't see another solution either.

**Comment by Penguin12335** [comment]
Weird, I use other seeds to test, they works well???
