### ISSUE TITLE
Messed up exits on Tutorial Vault

### ISSUE THREAD

**Issue by sigma144** [Penguin12335/Variety-Randomizer-2.0.1#3]
![Img1](https://user-images.githubusercontent.com/3487299/160941976-38999004-3514-4205-aef6-42c735e7584f.png)
Seed: 492713
See the white circles where the exits should be? The exits on this puzzle seem to be corrupted.

**Comment by Penguin12335** [comment]
I reduce to 1 Exit, It should work as intended
